# Generated by Django 5.1.1 on 2024-09-18 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonationrequest',
            old_name='date_requested',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='blooddonationrequest',
            name='details',
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='blood_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='municipality',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='region',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='request_type',
            field=models.CharField(choices=[('donating', 'Donating'), ('looking', 'Looking for')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blooddonationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
